pipeline {
    agent any

    tools {
        jdk 'JDK 11'           // Match the name from Jenkins tool config
        maven 'Maven 3.8.5'    // Match the name from Jenkins tool config
    }

    stages {
        stage('Clone') {
            steps {
                git 'https://github.com/muthapriyanka/Logparser.git'
            }
        }

        stage('Build') {
            steps {
                dir('logparser') {
                    sh 'mvn clean compile'
                }
            }
        }

        stage('Run') {
            steps {
                dir('logparser') {
                    sh 'mvn exec:java -Dexec.mainClass="com.logparser.Main"'
                }
            }
        }
    }
}
